In [15]:
import pandas as pd

df = pd.read_csv('HR_comma_sep.csv').drop(columns=['left'])
df

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,promotion_last_5years,Department,salary
0,0.38,0.53,2,157,3,0,0,sales,low
1,0.80,0.86,5,262,6,0,0,sales,medium
2,0.11,0.88,7,272,4,0,0,sales,medium
3,0.72,0.87,5,223,5,0,0,sales,low
4,0.37,0.52,2,159,3,0,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,0.40,0.57,2,151,3,0,0,support,low
14995,0.37,0.48,2,160,3,0,0,support,low
14996,0.37,0.53,2,143,3,0,0,support,low
14997,0.11,0.96,6,280,4,0,0,support,low
14998,0.37,0.52,2,158,3,0,0,support,low

In [16]:
df.describe()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,promotion_last_5years
count,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000
mean,0.612834,0.716102,3.803054,201.050337,3.498233,0.144610,0.021268
std,0.248631,0.171169,1.232592,49.943099,1.460136,0.351719,0.144281
min,0.090000,0.360000,2.000000,96.000000,2.000000,0.000000,0.000000
25%,0.440000,0.560000,3.000000,156.000000,3.000000,0.000000,0.000000
50%,0.640000,0.720000,4.000000,200.000000,3.000000,0.000000,0.000000
75%,0.820000,0.870000,5.000000,245.000000,4.000000,0.000000,0.000000
max,1.000000,1.000000,7.000000,310.000000,10.000000,1.000000,1.000000

In [17]:
df = df.drop(columns=['last_evaluation','number_project'])
df

,satisfaction_level,average_montly_hours,time_spend_company,Work_accident,promotion_last_5years,Department,salary
0,0.38,157,3,0,0,sales,low
1,0.80,262,6,0,0,sales,medium
2,0.11,272,4,0,0,sales,medium
3,0.72,223,5,0,0,sales,low
4,0.37,159,3,0,0,sales,low
...,...,...,...,...,...,...,...
14994,0.40,151,3,0,0,support,low
14995,0.37,160,3,0,0,support,low
14996,0.37,143,3,0,0,support,low
14997,0.11,280,4,0,0,support,low
14998,0.37,158,3,0,0,support,low

In [18]:
print(df['salary'].value_counts())
print(df['Department'].value_counts())

salary
low       7316
medium    6446
high      1237
Name: count, dtype: int64
Department
sales          4140
technical      2720
support        2229
IT             1227
product_mng     902
marketing       858
RandD           787
accounting      767
hr              739
management      630
Name: count, dtype: int64

In [19]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Department'] = le.fit_transform(df['Department'])
df['salary'] = le.fit_transform(df['salary'])

In [20]:
df

,satisfaction_level,average_montly_hours,time_spend_company,Work_accident,promotion_last_5years,Department,salary
0,0.38,157,3,0,0,7,1
1,0.80,262,6,0,0,7,2
2,0.11,272,4,0,0,7,2
3,0.72,223,5,0,0,7,1
4,0.37,159,3,0,0,7,1
...,...,...,...,...,...,...,...
14994,0.40,151,3,0,0,8,1
14995,0.37,160,3,0,0,8,1
14996,0.37,143,3,0,0,8,1
14997,0.11,280,4,0,0,8,1
14998,0.37,158,3,0,0,8,1

In [21]:
print(df['salary'].value_counts())
print(df['Department'].value_counts())

salary
1    7316
2    6446
0    1237
Name: count, dtype: int64
Department
7    4140
9    2720
8    2229
0    1227
6     902
5     858
1     787
2     767
3     739
4     630
Name: count, dtype: int64

Department: (jobrole)

sales          7
technical      9
support        8
IT             0
product_mng    6
marketing      5
RandD          1
accounting     2
hr             3
management     4

salary: 

low       1
medium    2
high      0

In [22]:
X = df.drop(columns=['satisfaction_level'])
y = df[['satisfaction_level']]

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [24]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_test,y_test)

C:\Users\prshi\anaconda3\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor()

In [25]:
y_pred = model.predict(X_test)
y_pred

array([0.6447    , 0.78514   , 0.393     , ..., 0.64346667, 0.6632    ,
       0.78826333])

In [26]:
model.score(X_test, y_test)

0.8375271708494582

In [27]:
#saving the trained model
import pickle
filename = "sat_pred.sav"
pickle.dump(model, open(filename,"wb"))

#loading the saved model
loaded_model = pickle.load(open('sat_pred.sav', 'rb'))